name: Enforce Folder Permissions and Auto-Merge

on:
  push:
    branches:
      - '*-branch' # Matches avishek-branch, moumita-branch, michael-branch

jobs:
  enforce-and-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2 # To compare commits
          token: ${{ secrets.GITHUB_TOKEN }} # For pushing to main

      - name: Check folder changes
        run: |
          USER=${{ github.actor }}
          declare -A USER_FOLDERS
          USER_FOLDERS["avishek-018"]="avishek"
          USER_FOLDERS["Moumita-Sen-Sarma"]="moumita"
          USER_FOLDERS["MikeLilley"]="michael"
          ALLOWED_FOLDER=${USER_FOLDERS[$USER]}
          if [ -z "$ALLOWED_FOLDER" ]; then
            echo "Error: No folder assigned to user $USER"
            exit 1
          fi
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          for FILE in $CHANGED_FILES; do
            if [[ "$FILE" != "$ALLOWED_FOLDER/"* ]]; then
              echo "Error: $USER tried to modify $FILE, but is only allowed in $ALLOWED_FOLDER/"
              exit 1
            fi
          done

      - name: Auto-merge to main
        run: |
          git fetch origin main
          git checkout main
          git merge --no-ff ${{ github.ref_name }} -m "Auto-merge from ${{ github.ref_name }}"
          git push origin main
