name: Enforce Folder Permissions and Auto-Merge

on:
  push:
    branches:
      - avishek-branch
      - moumita-branch
      - michael-branch

jobs:
  enforce-and-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check folder changes
        run: |
          USER=${{ github.actor }}
          declare -A USER_FOLDERS
          USER_FOLDERS["avishek-018"]="avishek"
          USER_FOLDERS["Moumita-Sen-Sarma"]="moumita"
          USER_FOLDERS["MikeLilley"]="michael"
          ALLOWED_FOLDER=${USER_FOLDERS[$USER]}
          if [ -z "$ALLOWED_FOLDER" ]; then
            echo "Error: No folder assigned to user $USER"
            exit 1
          fi
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          for FILE in $CHANGED_FILES; do
            if [[ "$FILE" != "$ALLOWED_FOLDER/"* ]]; then
              echo "Error: $USER tried to modify $FILE, but is only allowed in $ALLOWED_FOLDER/"
              exit 1
            fi
          done

      - name: Create Pull Request and Auto-Merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH=${{ github.ref_name }}
          gh pr create --base main --head $BRANCH --title "Auto-merge from $BRANCH" --body "Changes validated and auto-merged" || true
          gh pr merge --auto --merge $BRANCH
